using IdentityExample.Data;
using Microsoft.AspNetCore.Identity;

namespace IdentityExample.ServicesConfiguration
{
    public static class IdentityConfiguration
    {
        public static void RegisterIdentityServices(this IServiceCollection services)
        {
            // AddIdentity registers the services (SignInManager, UserManager...)
            services.AddIdentity<IdentityUser, IdentityRole>(config =>
            {
                config.Password.RequiredLength = 4;
                config.Password.RequireDigit = false;
                config.Password.RequireNonAlphanumeric = false;
                config.Password.RequireUppercase = false;
                config.SignIn.RequireConfirmedEmail = true;
            })
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders();
        }

        public static void RegisterCookies(this IServiceCollection services)
        {
            // This is how we configure the cookie generated by the Identity SignInManager
            services.ConfigureApplicationCookie(config =>
            {
                config.Cookie.Name = "Identity.Cookie";
                config.LoginPath = "/Home/Login";
            });
        }
    }
}
